# Netlify config for Next.js (App Router supported)
[build]
  command = "npm run build"
  # Note: don't set `publish` here; the Next.js Netlify plugin handles it.

[[plugins]]
  package = "@netlify/plugin-nextjs"
